import "./globals.css";
import { Inter } from "next/font/google";
import SessionProvider from "../context/AuthContext"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KXKDA | Chat",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#fafafa] dark:bg-[#070707] dark:text-[#fafafa]`}>
        <SessionProvider>
            {children}
        </SessionProvider>
      </body>
    </html>
  );
}
